spring:
  datasource:
    password: testtest
    url: jdbc:mysql://localhost:3306/blogdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Moscow
    username: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

