spring:
  datasource:
    password: testtest
    url: jdbc:mysql://localhost:3306/blogdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

